### ISSUE TITLE
LogUtil doesn't seem to work

### ISSUE THREAD

**Issue by avukich** [intellinote/inote-util#1]
```
var Util = require('inote-util').Util;
Util.tlog("hello world");
```

throws

```
/Users/avukich/projects/inote-partner-admin/server.js:9
Util.tlog("hello world");
     ^

TypeError: Util.tlog is not a function
    at Object.<anonymous> (/Users/avukich/projects/inote-partner-admin/server.js:9:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

and a further test using:

```
var Util = require('inote-util').Util;

try {
    Util.tlog("hello tlog");
} catch (e) {
    console.log(e);
}
try {
    Util.terr("hello terr");
} catch (e) {
    console.log(e);
}
try {
    Util.tplog("hello tplog");
} catch (e) {
    console.log(e);
}
try {
    Util.tperr("hello tperr");
} catch (e) {
    console.log(e);
}
```

resulted in:

```
[TypeError: Util.tlog is not a function]
[TypeError: Util.terr is not a function]
[TypeError: Util.tplog is not a function]
[TypeError: Util.tperr is not a function]
```

**Comment by rodw** [comment]
Oops. Sorry @avukich that looks like a documentation bug. Those methods are not in `Util` but in `LogUtil`.

Change your code to:

``` js
var LogUtil = require('inote-util').LogUtil;
LogUtil.tlog("hello tlog");
// etc.
```

and it should work.

**Comment by rodw** [comment]
I can't find any place where we explicitly say `Util.tlog` (rather than `LogUtil.tlog`) but I've added a brief "Using" section to the README that I hope makes the usage a little more clear.

I'm closing this for now, please re-open or otherwise let me know if there is a specific place in the documentation or example code where we lead the reader astray on this.

(Also, since @avukich is a member of the Intellinote team, you probably have direct write access to this repo. If you don't let me know and I'll hook you up :) )
